import React from 'react';
export const metadata = {
    title: 'add-product dashboard | Next Hero',
    description: 'Generated by create next app',
}

const AddProductPage = () => {
    return (
        <div>   
 AddProductPage
        </div>
    );
};

export default AddProductPage;