import React from 'react';
export const metadata = {
    title: 'abou | Next Hero',
    description: 'Generated by create next app',
}

const AboutPage = () => {
    return <div>about Paeg</div>;
};

export default AboutPage;