import Navber from '@/components/section/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Banner from '@/components/section/Banner'
import AboutMe from '@/components/section/AboutMe'
import WhatIDo from '@/components/section/WhatIDo'
import EducationSummary from '@/components/section/EducationSummary'
import LetsConnect from '@/components/section/LetsConnect'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Hero',
  description: 'Generated by create next app',
}

const RootLayout= ({ children })=> {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <Navber></Navber>
      <Banner></Banner>
      <AboutMe></AboutMe>
      <WhatIDo></WhatIDo>
      <EducationSummary></EducationSummary>
      <LetsConnect></LetsConnect>
    </html>
  )
}

export default RootLayout;
