import React from 'react';
export const metadata = {
    title: 'profile | Next Hero',
    description: 'Generated by create next app',
}

const ProfilePage = () => {
    return (
        <div>
           profilr page 
        </div>
    );
};

export default ProfilePage;